/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.agrohelp;

import javax.swing.JOptionPane;

/**
 *
 * @author SteNocheli
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        super("AgroHelp");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomePerfilTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        sexoComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        voltarButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        userTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        senhaPasswordField = new javax.swing.JPasswordField();
        dataNascimentoTextField = new javax.swing.JFormattedTextField();
        cpfTextField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(515, 738));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(214, 214, 196));
        jLabel1.setText("Nome Completo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 80, 240, 16);

        nomePerfilTextField.setBackground(new java.awt.Color(214, 214, 196));
        nomePerfilTextField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        nomePerfilTextField.setForeground(new java.awt.Color(44, 50, 15));
        nomePerfilTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nomePerfilTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomePerfilTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomePerfilTextField);
        nomePerfilTextField.setBounds(110, 100, 280, 30);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(214, 214, 196));
        jLabel2.setText("CPF");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 140, 140, 16);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(214, 214, 196));
        jLabel3.setText("Data de Nascimento ( AAAA/MM/DD )");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 200, 240, 16);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(214, 214, 196));
        jLabel4.setText("E-mail");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 320, 180, 16);

        emailTextField.setBackground(new java.awt.Color(214, 214, 196));
        emailTextField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(44, 50, 15));
        emailTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(emailTextField);
        emailTextField.setBounds(110, 340, 280, 30);

        sexoComboBox.setBackground(new java.awt.Color(214, 214, 196));
        sexoComboBox.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        sexoComboBox.setForeground(new java.awt.Color(44, 50, 15));
        sexoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prefiro Não Informar", "Feminino", "Masculino", "Outros" }));
        sexoComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sexoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(sexoComboBox);
        sexoComboBox.setBounds(110, 280, 280, 24);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(214, 214, 196));
        jLabel6.setText("Sexo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 260, 26, 16);

        voltarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/sair.png"))); // NOI18N
        voltarButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 214, 196)));
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarButton);
        voltarButton.setBounds(110, 580, 280, 40);

        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/login.png"))); // NOI18N
        loginButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(214, 214, 196)));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(110, 530, 280, 40);

        userTextField.setBackground(new java.awt.Color(214, 214, 196));
        userTextField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        userTextField.setForeground(new java.awt.Color(44, 50, 15));
        userTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(userTextField);
        userTextField.setBounds(110, 400, 280, 30);

        jLabel7.setForeground(new java.awt.Color(214, 214, 196));
        jLabel7.setText("Usuário");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 380, 220, 16);

        jLabel8.setForeground(new java.awt.Color(214, 214, 196));
        jLabel8.setText("Senha");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 440, 270, 16);

        senhaPasswordField.setBackground(new java.awt.Color(214, 214, 196));
        senhaPasswordField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        senhaPasswordField.setForeground(new java.awt.Color(44, 50, 15));
        senhaPasswordField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        senhaPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(senhaPasswordField);
        senhaPasswordField.setBounds(110, 460, 280, 30);

        dataNascimentoTextField.setBackground(new java.awt.Color(214, 214, 196));
        dataNascimentoTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dataNascimentoTextField.setForeground(new java.awt.Color(44, 50, 15));
        try {
            dataNascimentoTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataNascimentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascimentoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(dataNascimentoTextField);
        dataNascimentoTextField.setBounds(110, 220, 280, 30);

        cpfTextField.setBackground(new java.awt.Color(214, 214, 196));
        cpfTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cpfTextField.setForeground(new java.awt.Color(44, 50, 15));
        try {
            cpfTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(cpfTextField);
        cpfTextField.setBounds(110, 156, 280, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/background2.2.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 520, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomePerfilTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePerfilTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePerfilTextFieldActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        // TODO add your handling code here:
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        String login = userTextField.getText();
        String senha = new String(senhaPasswordField.getPassword());
        String nomePerfil = nomePerfilTextField.getText();
        String email = emailTextField.getText();
        int dataNascimento = Integer.parseInt((dataNascimentoTextField.getText()).replace("/", ""));
        long CPF = Long.parseLong((cpfTextField.getText()).replace(".", "").replace("-", ""));
        int sexoOpcao = sexoComboBox.getSelectedIndex();
        char sexo;
        if (sexoOpcao == 0) {
            sexo = 'N';
        } else if (sexoOpcao == 1) {
            sexo = 'F';
        } else if (sexoOpcao == 2) {
            sexo = 'M';
        } else {
            sexo = 'O';
        }

        try {
            Usuario usuario = new Usuario(login, senha);
            DAO dao = new DAO();
            usuario.setEmail(email);
            usuario.setNomePerfil(nomePerfil);
            usuario.setDataNascimento(dataNascimento);
            usuario.setCPF(CPF);
            usuario.setSexo(sexo);

            if (dao.existe(usuario)) {
                JOptionPane.showMessageDialog(null, "Usuário já cadastrado!");
            } else if (dao.existe(usuario) == false) {
                dao.cadastrar(usuario);
                dao.carregarDados(usuario);
                JOptionPane.showMessageDialog(null, "Usuário cadastrado!");
                JOptionPane.showMessageDialog(null, "Bem vindo, " + usuario.getNomePerfil() + "!");
                DashboardTela dt = new DashboardTela(usuario);
                dt.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuário inválido");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problemas técnicos. Tente novamente mais tarde");
            e.printStackTrace();
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void senhaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaPasswordFieldActionPerformed

    private void sexoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoComboBoxActionPerformed

    private void dataNascimentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascimentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascimentoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField cpfTextField;
    private javax.swing.JFormattedTextField dataNascimentoTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField nomePerfilTextField;
    private javax.swing.JPasswordField senhaPasswordField;
    private javax.swing.JComboBox<String> sexoComboBox;
    private javax.swing.JTextField userTextField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
